//------------------------------------------------------------------------------
// <auto-generated>
//     這段程式碼是由工具產生的。
//     執行階段版本:4.0.30319.42000
//
//     對這個檔案所做的變更可能會造成錯誤的行為，而且如果重新產生程式碼，
//     變更將會遺失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Quick_Paste_Tool.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "15.6.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("範本1;範本1的文字內容")]
        public string btn1_pref {
            get {
                return ((string)(this["btn1_pref"]));
            }
            set {
                this["btn1_pref"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("範本2;範本2的文字內容")]
        public string btn2_pref {
            get {
                return ((string)(this["btn2_pref"]));
            }
            set {
                this["btn2_pref"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("範本3;範本3的文字內容")]
        public string btn3_pref {
            get {
                return ((string)(this["btn3_pref"]));
            }
            set {
                this["btn3_pref"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("範本4;範本4的文字內容")]
        public string btn4_pref {
            get {
                return ((string)(this["btn4_pref"]));
            }
            set {
                this["btn4_pref"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("範本5;範本5的文字內容")]
        public string btn5_pref {
            get {
                return ((string)(this["btn5_pref"]));
            }
            set {
                this["btn5_pref"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("範本6;範本6的文字內容")]
        public string btn6_pref {
            get {
                return ((string)(this["btn6_pref"]));
            }
            set {
                this["btn6_pref"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("範本7;範本7的文字內容")]
        public string btn7_pref {
            get {
                return ((string)(this["btn7_pref"]));
            }
            set {
                this["btn7_pref"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("範本8;範本8的文字內容")]
        public string btn8_pref {
            get {
                return ((string)(this["btn8_pref"]));
            }
            set {
                this["btn8_pref"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("範本9;範本9的文字內容")]
        public string btn9_pref {
            get {
                return ((string)(this["btn9_pref"]));
            }
            set {
                this["btn9_pref"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("範本10;範本10的文字內容")]
        public string btn10_pref {
            get {
                return ((string)(this["btn10_pref"]));
            }
            set {
                this["btn10_pref"] = value;
            }
        }
    }
}
